[build]
command = """
curl -sL https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | tar xz && \
./zola build
"""
publish = "public"

[build.environment]
ZOLA_VERSION = "0.17.2"  # Use your desired Zola version